[workspace]

members = [
    "amethyst-example",
    "cargo-spatial",
    "project-example",
    "spatialos-sdk",
    "spatialos-sdk-code-generator",
    "spatialos-sdk-sys",
    "spatialos-sdk-tools",
    "test-suite"
]
